name: libstone
version: 0.1.0.0
maintainer: Gavin Zhao <me@gzgz.dev>
license: MPL-2.0
homepage: https://github.com/GZGavinZhao/moss.hs
category: Codec

language: GHC2021

dependencies:
  - base == 4.*
  - array
  - binary
  - bytestring
  - placeholders
  - pretty-simple

ghc-options: -threaded

library:
  source-dirs:
    - src
  other-modules:
    - Codec.Stone.Utils.Decode
    - Codec.Stone.Utils.DeriveEnum
  dependencies:
    - template-haskell
    - text
    - wide-word
    - zstd
  default-extensions:
    - RecordWildCards
  other-extensions:
    - TemplateHaskell
    - OverloadedStrings

tests:
  spec:
    main: Spec.hs
    source-dirs:
      - test
    dependencies:
      - hspec == 2.*
      - QuickCheck
      - libstone
    build-tools:
      - hspec-discover
